import 'dart:io';

import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/material.dart';
import 'package:flutter_callkit_incoming/entities/call_event.dart';
import 'package:flutter_callkit_incoming/flutter_callkit_incoming.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:orcanet/services/callService.dart';
import 'package:orcanet/index/pageIndex.dart';
import 'package:orcanet/index/serviceIndex.dart';

final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin = FlutterLocalNotificationsPlugin();

class Callnotifservice {
  final dynamic context;
  const Callnotifservice({required this.context});

  Future<void> checkAndNavigationCallingPage() async {
    // 1. Listen for current calls (The "Closed App" Fix)
    // We wait for the build to finish, otherwise Navigator fails
    WidgetsBinding.instance.addPostFrameCallback((_) async {
      
      var currentCalls = await FlutterCallkitIncoming.activeCalls();
      
      if (currentCalls != null && currentCalls.isNotEmpty) {
        print("--> Found active call on startup!"); 
        var callData = currentCalls[0];
        _handleNavigation(callData);
      }
    });

    // 2. Listen for new events (The "Background/Foreground" Fix)
    FlutterCallkitIncoming.onEvent.listen((event) {
      if (event != null) {
        switch (event.event) {
          case Event.actionCallAccept:
            print("--> User clicked Accept!");
            _handleNavigation(event.body);
            break;
            
          case Event.actionCallDecline:
            print("--> User clicked Decline!");
            // Optionally hangup here
            break;
            
          default:
            break;
        }
      }
    });
  }

  void _handleNavigation(dynamic data) {
      // DEBUG: Print what data we actually got
      print("--> Navigating with data: $data");

      // 1. Try to find the Channel ID (It might be 'id' or inside 'extra')
      String? channelId = data['id']; 
      
      // Fallback: If 'id' is just the UUID generated by Android, look for our 'uuid'
      if (data['extra'] != null && data['extra']['uuid'] != null) {
        channelId = data['extra']['uuid'];
      }

      // 2. Determine Call Type (Video vs Audio)
      // CallKit usually sends type as 0 (Audio) or 1 (Video)
      bool isVideo = false;
      if (data['type'] == 1 || data['type'] == '1') {
        isVideo = true;
      }
      // Or check our custom data
      if (data['extra'] != null && data['extra']['hasVideo'] == "true") {
        isVideo = true;
      }

      // 3. Navigate
      if (isVideo) {
            // IT IS A VIDEO CALL -> Go to Video File
            Navigator.push(
              context,
              MaterialPageRoute(
                builder: (_) => VideoCallPage( // <--- Your Video Widget
                    channelId: channelId!
                )
              )
            );
          } else {
            // IT IS A VOICE CALL -> Go to Voice File
            Navigator.push(
              context,
              MaterialPageRoute(
                builder: (_) => VoiceCallPage( // <--- Your Voice Widget
                    channelId: channelId!,
                    starterId: FirebaseAuth.instance.currentUser!.uid,
                )
              )
            );
          }
}

void listenForCallEvents() {
    FlutterCallkitIncoming.onEvent.listen((CallEvent? event) {
      if (event == null) return;

      switch (event.event) {
        case Event.actionCallAccept:
          // User clicked "Answer"
          // Get data from the event
          String channelId = event.body['id'];
          // String callerId = event.body['number']; (We mapped 'handle' to callerId)
          int callType = event.body['type'];
          
          // NAVIGATE TO AGORA PAGE
          if (callType == 1) {
            // IT IS A VIDEO CALL -> Go to Video File
            Navigator.push(
              context,
              MaterialPageRoute(
                builder: (_) => VideoCallPage( // <--- Your Video Widget
                    channelId: channelId
                )
              )
            );
          } else {
            // IT IS A VOICE CALL -> Go to Voice File
            Navigator.push(
              context,
              MaterialPageRoute(
                builder: (_) => VoiceCallPage( // <--- Your Voice Widget
                    channelId: channelId,
                    starterId: FirebaseAuth.instance.currentUser!.uid,
                )
              )
            );
          }
          break;

        case Event.actionCallDecline:
          // User clicked "Decline"
          // You might want to send a "Rejected" message to Firestore here
          break;
          
        default:
          break;
      }
    });
  }

  void setupNotification() async {
    FirebaseMessaging messaging = FirebaseMessaging.instance;
    NotificationSettings settings = await messaging.requestPermission(
      alert: true,
      badge: true,
      sound: true,
    );

    FirebaseMessaging.onMessage.listen((RemoteMessage message) {
    if (message.data['type'] == 'call_offer') {
        // INSTEAD of showing a banner, show the Full Screen UI
        CallService.showIncomingCall(
            uuid: message.data['uuid'],
            callerName: message.data['callerName'] ?? "UnknownId",
            callerId: message.data['callerId'] ?? "000",
            hasVideo: message.data['hasVideo'] == 'true',
        );
    } else {
        // Normal chat notification logic...
    }
});

    if (settings.authorizationStatus == AuthorizationStatus.authorized) {
      print('User granted permission');
    }

    const AndroidInitializationSettings initializationSettingsAndroid =
        AndroidInitializationSettings('@mipmap/notif_icon');

    const DarwinInitializationSettings initializationSettingsIOS =
        DarwinInitializationSettings();

    const InitializationSettings initializationSettings = InitializationSettings(
      android: initializationSettingsAndroid,
      iOS: initializationSettingsIOS,
    );

    await flutterLocalNotificationsPlugin.initialize(
      initializationSettings,
      onDidReceiveNotificationResponse: (details) {
        // This handles when a user taps on a LOCAL notification (Foreground)
        print("Tapped local notification: ${details.payload}");
      },
    );

    if (Platform.isAndroid) {
      const AndroidNotificationChannel channel = AndroidNotificationChannel(
        'high_importance_channel', // id
        'High Importance Notifications', // title
        description: 'This channel is used for important notifications.', 
        importance: Importance.max,
      );

      await flutterLocalNotificationsPlugin
          .resolvePlatformSpecificImplementation<
              AndroidFlutterLocalNotificationsPlugin>()
          ?.createNotificationChannel(channel);
    }



    FirebaseMessaging.onMessage.listen((RemoteMessage message) {
      print(message.notification?.body);

      if (message.notification != null && Platform.isAndroid) {
        flutterLocalNotificationsPlugin.show(
          message.hashCode,
          message.notification!.title,
          message.notification!.body,
          const NotificationDetails(
            android: AndroidNotificationDetails(
              'high_importance_channel',
              'High Importance Notifications',
              icon: '@mipmap/notif_icon', // Your icon
            ),
          ),
        );
      }
    });

    FirebaseMessaging.onMessageOpenedApp.listen((RemoteMessage message) {
      print("I just tapped a notification wtf just happened?!!?!!");
    });

    FirebaseMessaging.instance.getInitialMessage().then((RemoteMessage? message) {
      if (message != null) {
        print("App launched from Terminated state by notification!");
        // Navigate to the chat screen
        // Note: You might need to delay this slightly or use a global navigator key
        // if your Context isn't fully ready yet.
      }
    });

  }
}