// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh0PZOSAQOYbNvlpRBDKvSI96A98dlq9M',
    appId: '1:1026530209585:web:01a1b0860e7ed1a4ee8a10',
    messagingSenderId: '1026530209585',
    projectId: 'orcanet-4612',
    authDomain: 'orcanet-4612.firebaseapp.com',
    storageBucket: 'orcanet-4612.firebasestorage.app',
    measurementId: 'G-WB0NS6V152',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2z_dwcv6dJX4AYmizVaUJFtosJWOdleM',
    appId: '1:1026530209585:android:b15df7bd3a18fc52ee8a10',
    messagingSenderId: '1026530209585',
    projectId: 'orcanet-4612',
    storageBucket: 'orcanet-4612.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ39WbkTvwdz2gkrvsIBpV4YXGJ_2MiEs',
    appId: '1:1026530209585:ios:6f9d031545843179ee8a10',
    messagingSenderId: '1026530209585',
    projectId: 'orcanet-4612',
    storageBucket: 'orcanet-4612.firebasestorage.app',
    androidClientId: '1026530209585-4re9nqfc6cscjpd6np1ut08olp9e6h56.apps.googleusercontent.com',
    iosClientId: '1026530209585-59gc6o1j6th2p53lu00snvcirr74mhbr.apps.googleusercontent.com',
    iosBundleId: 'com.sailors.orcanet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ39WbkTvwdz2gkrvsIBpV4YXGJ_2MiEs',
    appId: '1:1026530209585:ios:6f9d031545843179ee8a10',
    messagingSenderId: '1026530209585',
    projectId: 'orcanet-4612',
    storageBucket: 'orcanet-4612.firebasestorage.app',
    androidClientId: '1026530209585-4re9nqfc6cscjpd6np1ut08olp9e6h56.apps.googleusercontent.com',
    iosClientId: '1026530209585-59gc6o1j6th2p53lu00snvcirr74mhbr.apps.googleusercontent.com',
    iosBundleId: 'com.sailors.orcanet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBh0PZOSAQOYbNvlpRBDKvSI96A98dlq9M',
    appId: '1:1026530209585:web:974892c8a4e9b6b9ee8a10',
    messagingSenderId: '1026530209585',
    projectId: 'orcanet-4612',
    authDomain: 'orcanet-4612.firebaseapp.com',
    storageBucket: 'orcanet-4612.firebasestorage.app',
    measurementId: 'G-EJ856316H1',
  );
}
